/* =====================================================
   DATABASE DESA SEPINGGAN GELIK
   GOOGLE APPS SCRIPT
   Database hanya digunakan untuk data BERANDA.
===================================================== */
const SHEET_NAME = "Sheet1";
function getSheet(){ const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME); if(!s) throw new Error("Sheet1 tidak ditemukan."); return s; }
function setupSheet(){ const s=getSheet(); const h=["ID","Judul","Kategori","Deskripsi","URL Gambar"]; s.getRange(1,1,1,5).setValues([h]); if(s.getLastRow()===1){s.getRange(2,1,3,5).setValues([["1","Keindahan Sawah","Keindahan","Pemandangan sawah Desa Sepinggan Gelik yang asri dan menyejukkan.","./sawah.jpg"],["2","Masyarakat","Masyarakat","Kehidupan masyarakat Desa Sepinggan Gelik yang penuh kebersamaan.","./masyarakat.jpg"],["3","Tempat Ibadah","Keagamaan","Masjid sebagai salah satu tempat ibadah masyarakat Desa Sepinggan Gelik.","./masjid.jpg"]]);} return {success:true,message:"Sheet berhasil disiapkan."}; }
function getData(){ const s=getSheet(), v=s.getDataRange().getValues(); if(v.length<=1)return []; return v.slice(1).filter(r=>r.some(c=>String(c).trim()!=="")).map(r=>({id:String(r[0]??""),judul:String(r[1]??""),kategori:String(r[2]??""),deskripsi:String(r[3]??""),gambar:String(r[4]??"")})); }
function jsonResponse(o,cb){const t=JSON.stringify(o); return ContentService.createTextOutput(cb?cb+"("+t+");":t).setMimeType(cb?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON);}
function doGet(e){try{const p=e?.parameter||{}, a=p.action||"get"; if(a==="setup")return jsonResponse(setupSheet(),p.callback); if(a==="get")return jsonResponse({success:true,data:getData()},p.callback); if(a==="tambah"){getSheet().appendRow([String(Date.now()),p.judul||"",p.kategori||"",p.deskripsi||"",p.gambar||""]);return jsonResponse({success:true,message:"Data berhasil ditambahkan."},p.callback);} if(a==="edit")return jsonResponse(editData(p),p.callback); if(a==="hapus")return jsonResponse(deleteData(p.id),p.callback); return jsonResponse({success:false,message:"Action tidak ditemukan."},p.callback);}catch(err){return jsonResponse({success:false,message:String(err)},e?.parameter?.callback);}}
function editData(p){const s=getSheet(),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++){if(String(v[i][0])===String(p.id)){s.getRange(i+1,2,1,4).setValues([[p.judul||"",p.kategori||"",p.deskripsi||"",p.gambar||""]]);return{success:true,message:"Data berhasil diperbarui."};}}return{success:false,message:"Data tidak ditemukan."};}
function deleteData(id){const s=getSheet(),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++){if(String(v[i][0])===String(id)){s.deleteRow(i+1);return{success:true,message:"Data berhasil dihapus."};}}return{success:false,message:"Data tidak ditemukan."};}
function doPost(e){try{const d=JSON.parse(e.postData.contents||"{}"), p=d; if(p.action==="tambah")return jsonResponse(doGet({parameter:{action:"tambah",judul:p.judul,kategori:p.kategori,deskripsi:p.deskripsi,gambar:p.gambar}})); if(p.action==="edit")return jsonResponse(doGet({parameter:{action:"edit",id:p.id,judul:p.judul,kategori:p.kategori,deskripsi:p.deskripsi,gambar:p.gambar}})); if(p.action==="hapus")return jsonResponse(doGet({parameter:{action:"hapus",id:p.id}})); return jsonResponse({success:false,message:"Action tidak ditemukan."});}catch(err){return jsonResponse({success:false,message:String(err)});}}
